# Canonical material taxonomy — the source of truth for all tracker rows.
# Each entry defines one material that can appear in any building.

MATERIAL_TAXONOMY = [
    # ── ROOF ──────────────────────────────────────────────────────────────────
    {
        "material_name": "SBS waterproofing membrane",
        "system": "Roof",
        "category": "Waterproofing",
        "adnoc_spec_ref": "AGES-SP-01-017 / GG-000-20-40-007",
        "international_standard": "ASTM D6163",
        "unit": "m²",
        "default_description": "4mm torch-applied SBS modified bitumen membrane for roofs",
        "keywords": ["sbs", "waterproof", "membrane", "torch", "bitumen", "modified"],
    },
    {
        "material_name": "Bitumen primer",
        "system": "Roof",
        "category": "Waterproofing",
        "adnoc_spec_ref": "AGES-SP-01-017",
        "international_standard": "ASTM D41",
        "unit": "m²",
        "default_description": "Cold-applied bitumen primer conforming to ASTM D41",
        "keywords": ["primer", "bitumen", "cold applied"],
    },
    {
        "material_name": "Geotextile separation layer",
        "system": "Roof",
        "category": "Waterproofing",
        "adnoc_spec_ref": "AGES-SP-01-017 / GG-000-20-40-007",
        "international_standard": "EN 13252",
        "unit": "m²",
        "default_description": "Non-woven polypropylene geotextile, min 200 g/m², separation layer",
        "keywords": ["geotextile", "separation", "nonwoven", "polypropylene", "filter"],
    },
    {
        "material_name": "Roof insulation board (XPS/PIR)",
        "system": "Roof",
        "category": "Insulation",
        "adnoc_spec_ref": "AGES-SP-01-017",
        "international_standard": "ASTM C578 / EN 13163",
        "unit": "m²",
        "default_description": "Extruded polystyrene (XPS) or PIR insulation board, min 50mm thick",
        "keywords": ["insulation", "xps", "pir", "extruded", "polystyrene", "thermal"],
    },
    {
        "material_name": "Roof paving / protection screed",
        "system": "Roof",
        "category": "Roof Finish",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "",
        "unit": "m²",
        "default_description": "50mm cement:sand screed or concrete protection slab over waterproofing",
        "keywords": ["paving", "screed", "protection", "slab", "concrete roof", "pavement"],
    },
    {
        "material_name": "Roof drainage outlets",
        "system": "Roof",
        "category": "Roof Drainage",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "BS EN 1253",
        "unit": "no.",
        "default_description": "Cast iron roof drainage outlets with overflow provisions",
        "keywords": ["drain", "outlet", "overflow", "parapet", "downpipe", "gutter"],
    },
    # ── EXTERNAL WALLS ────────────────────────────────────────────────────────
    {
        "material_name": "External wall coating / anti-carbonation paint",
        "system": "Walls",
        "category": "External Finishes",
        "adnoc_spec_ref": "AGES-SP-01-014",
        "international_standard": "ISO 12944",
        "unit": "m²",
        "default_description": "Anti-carbonation elastomeric coating on external RC walls, grooved finish",
        "keywords": ["external", "paint", "coating", "anti-carbonation", "elastomeric", "grooved"],
    },
    {
        "material_name": "Expansion joint sealant",
        "system": "Walls",
        "category": "Joints",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "ASTM C920",
        "unit": "m",
        "default_description": "Low-modulus non-sag elastomeric sealant at structural expansion joints (e.g. Masterseal NP150)",
        "keywords": ["sealant", "expansion joint", "elastomeric", "non-sag", "low modulus", "masterseal"],
    },
    {
        "material_name": "Compressible joint filler",
        "system": "Walls",
        "category": "Joints",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "ASTM D1751",
        "unit": "m",
        "default_description": "Pre-moulded compressible filler (Flexcell or equal) at expansion joints",
        "keywords": ["filler", "flexcell", "compressible", "foam", "joint filler", "expansion"],
    },
    {
        "material_name": "Internal wall paint / emulsion",
        "system": "Walls",
        "category": "Internal Finishes",
        "adnoc_spec_ref": "AGES-SP-01-014",
        "international_standard": "ISO 12944",
        "unit": "m²",
        "default_description": "Interior emulsion paint, 2 coats on plastered/rendered surfaces",
        "keywords": ["internal", "paint", "emulsion", "interior", "wall paint"],
    },
    {
        "material_name": "Internal plaster / render",
        "system": "Walls",
        "category": "Plaster / Mortar",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "",
        "unit": "m²",
        "default_description": "12mm cement:sand plaster on internal RC wall surfaces",
        "keywords": ["plaster", "render", "skim", "cement sand", "internal"],
    },
    # ── FLOORS ────────────────────────────────────────────────────────────────
    {
        "material_name": "Epoxy floor coating",
        "system": "Floor",
        "category": "Floor Finish",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "ASTM C307",
        "unit": "m²",
        "default_description": "Anti-static / chemical resistant epoxy floor coating, 2mm DFT",
        "keywords": ["epoxy", "floor", "coating", "anti-static", "chemical resistant"],
    },
    {
        "material_name": "Ceramic / porcelain floor tile",
        "system": "Floor",
        "category": "Floor Finish",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "ISO 13006",
        "unit": "m²",
        "default_description": "600×600mm porcelain floor tile, R11 anti-slip rating, on cement adhesive",
        "keywords": ["tile", "ceramic", "porcelain", "floor tile", "anti-slip"],
    },
    {
        "material_name": "Raised access floor system",
        "system": "Floor",
        "category": "Floor System",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "EN 12825",
        "unit": "m²",
        "default_description": "Steel raised access floor panels on adjustable pedestals, min 600mm module",
        "keywords": ["raised", "access floor", "pedestal", "false floor", "computer floor"],
    },
    # ── CEILINGS ──────────────────────────────────────────────────────────────
    {
        "material_name": "Suspended ceiling system (mineral fibre tiles)",
        "system": "Ceiling",
        "category": "Ceiling",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "EN 13964",
        "unit": "m²",
        "default_description": "600×600mm mineral fibre ceiling tiles on metal grid suspension system",
        "keywords": ["ceiling", "suspended", "mineral fibre", "acoustic", "grid", "tiles"],
    },
    # ── DOORS ─────────────────────────────────────────────────────────────────
    {
        "material_name": "Blast-rated / fire-rated steel door",
        "system": "Doors",
        "category": "Doors",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "BS EN 1634-1",
        "unit": "no.",
        "default_description": "Fire and blast rated steel door set with hardware; rating per door schedule",
        "keywords": ["door", "steel door", "blast", "fire rated", "metal door", "rated door"],
    },
    {
        "material_name": "Aluminium window / louvre",
        "system": "Doors",
        "category": "Doors",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "BS 6375",
        "unit": "no.",
        "default_description": "Aluminium-framed window or louvre set, thermally broken, weather sealed",
        "keywords": ["window", "louvre", "aluminium", "aluminum", "glazing", "frame"],
    },
    # ── PARTITIONS ────────────────────────────────────────────────────────────
    {
        "material_name": "Gypsum board partition system",
        "system": "Partitions",
        "category": "Partitions",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "ASTM C36",
        "unit": "m²",
        "default_description": "Double-layer 12.5mm gypsum board on metal stud frame, fire-rated",
        "keywords": ["gypsum", "drywall", "partition", "plasterboard", "stud", "metal stud"],
    },
    # ── PROTECTION ────────────────────────────────────────────────────────────
    {
        "material_name": "Cathodic protection system",
        "system": "Substructure Protection",
        "category": "Protection",
        "adnoc_spec_ref": "AGES-SP-01-012",
        "international_standard": "NACE SP0169",
        "unit": "lot",
        "default_description": "HOLD – Cathodic protection system; vendor and scope TBD; earthing lug locations pending",
        "keywords": ["cathodic", "cp system", "protection", "anode", "sacrificial", "impressed current"],
    },
    {
        "material_name": "Earthing / grounding system",
        "system": "Substructure Protection",
        "category": "Protection",
        "adnoc_spec_ref": "GG-000-16-21-001",
        "international_standard": "IEC 62305 / BS 7430",
        "unit": "lot",
        "default_description": "Earthing installation per standard drawing HE-GG-000-16-21-001",
        "keywords": ["earthing", "grounding", "earth electrode", "earth conductor", "lightning"],
    },
    # ── EXTERNAL WORKS ────────────────────────────────────────────────────────
    {
        "material_name": "External paving / hardstanding",
        "system": "External Works",
        "category": "Paving",
        "adnoc_spec_ref": "AGES-SP-01-013",
        "international_standard": "",
        "unit": "m²",
        "default_description": "200mm reinforced concrete hardstanding around building perimeter",
        "keywords": ["paving", "hardstanding", "apron", "external", "perimeter", "concrete paving"],
    },
    {
        "material_name": "Chemical damp-proof membrane",
        "system": "Substructure Protection",
        "category": "Treatment",
        "adnoc_spec_ref": "AGES-SP-01-017",
        "international_standard": "BS 8102",
        "unit": "m²",
        "default_description": "Chemical damp-proof membrane applied to RC slab soffit, min 2 coats",
        "keywords": ["damp proof", "dpm", "moisture barrier", "tanking", "vapour barrier"],
    },
]

# Building-ID hints: maps document-number fragments → building tag
BUILDING_ID_HINTS = {
    "H4-278-20-22-001": "IES-201",
    "H4-278-17-23-001": "IES-201",
    "H4-278-17-23-004": "OMS-201",
    "H4-278-17-23-005": "OMS-201",
    "H4-278-20-29-001": "OMS-201",
    "H4-280-17-23-001": "SS-201",
    "H4-280-20-22-001": "SS-201",
    "H4-280-20-22-002": "SS-203",
    "H4-280-17-23-003": "SS-203",
    "H4-278-17-23-003": "IES-203",
    "H4-278-20-22-002": "IES-203",
    "H4-278-20-29-002": "OMS-203",
    "H2-278-17-23-001": "IES-202",
    "H2-278-20-22-001": "IES-202",
    "H2-280-17-23-001": "SS-202",
    "H2-280-20-22-001": "SS-202",
}

# Vendor fallbacks (used when spec extraction yields no vendors for a material)
VENDOR_FALLBACKS = {
    "SBS waterproofing membrane":      "BERGER PAINTS EMIRATES LTD CO (LLC) / Soprema / Fosroc / Sika",
    "Bitumen primer":                   "BERGER PAINTS EMIRATES LTD CO (LLC) / Soprema / Fosroc",
    "Geotextile separation layer":      "BERGER PAINTS EMIRATES LTD CO (LLC) / Soprema / Fiberweb",
    "Roof insulation board (XPS/PIR)":  "DOW Chemical / BASF Neopor / Kingspan",
    "Roof paving / protection screed":  "TBD",
    "Roof drainage outlets":            "Geberit / ACO / Wade",
    "External wall coating / anti-carbonation paint": "BERGER PAINTS EMIRATES / Jotun / AkzoNobel",
    "Expansion joint sealant":          "BASF MasterSeal / Sika / Fosroc",
    "Compressible joint filler":        "BASF MasterSeal / Sika / Fosroc",
    "Internal wall paint / emulsion":   "BERGER PAINTS EMIRATES / Jotun / AkzoNobel",
    "Internal plaster / render":        "Lafarge / Knauf / Parex",
    "Epoxy floor coating":              "BASF MasterTop / Sika / Fosroc",
    "Ceramic / porcelain floor tile":   "RAK Ceramics / Porcelanosa / Al Anwar",
    "Raised access floor system":       "Kingspan / Lindner / Tate",
    "Suspended ceiling system (mineral fibre tiles)": "Armstrong / Rockfon / Saint-Gobain",
    "Blast-rated / fire-rated steel door": "CUPRUM / KRAL CELIK / Alutech",
    "Aluminium window / louvre":        "CUPRUM / Schüco / Reynaers",
    "Gypsum board partition system":    "Knauf / Saint-Gobain Gyproc / USG",
    "Cathodic protection system":       "CORRPRO / Cathodic Protection Co. (CPC) / MATCOR",
    "Earthing / grounding system":      "Per ADNOC-approved electrical vendor list",
    "External paving / hardstanding":   "TBD",
    "Chemical damp-proof membrane":     "Fosroc / Sika / BASF",
}

# Default project metadata
DEFAULT_PROJECT_METADATA = {
    "project_name": "ADNOC Gas – Habshan 4 Long Term Execute Stage",
    "owner": "ADNOC",
    "epcm": "AMEC International Ltd",
    "contractor": "TBD",
    "sub_contractor": "TBD",
    "project_no": "30201-50150-LT-HE",
}

# Status defaults for all new rows
STATUS_DEFAULTS = {
    "submittal_status": "Pending",
    "consultant_approval": "Pending",
    "client_approval": "Pending",
    "avl_status": "Available",
    "po_status": "RFQ",
    "production_status": "Not Started",
    "delivery_status": "Not Delivered",
    "site_status": "Not Installed",
    "installation_status": "Not Started",
    "brand": "TBD",
    "origin": "TBD",
}
